In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('/Users/tongtongtot/Dropbox/ALL_DATASETS_repurposing/alprenolol/source_data.csv')

In [3]:
data

,Unnamed: 0,ST3GAL2,NOTCH2,GRPEL1,SHC2,MAGEA8,GNA14,KRTCAP2,CEP44,EHD2,...,SYT2,LAMTOR3,TLN2,FLT1,SHISA9,SUN3,C20ORF96,TNFSF4,CEP19,SPDYA
0,src_cell_1,3.619056,4.508007,4.982375,1.971839,0.832168,0.408579,8.792251,2.304922,3.508259,...,1.385265,5.963381,1.587457,0.821088,2.823237,0.257190,0.871458,0.567345,4.829073,2.127415
1,src_cell_2,1.920194,3.943391,4.943164,-0.147784,1.272182,0.828138,7.492292,2.824855,2.523076,...,0.193125,4.714866,3.964176,0.149162,1.018652,-0.072578,1.684920,-0.351311,-0.034724,0.153508
2,src_cell_3,2.462381,3.940544,6.744090,2.080098,0.065120,-0.607527,8.450511,3.067507,3.527180,...,-0.884180,4.349430,1.279788,0.499042,-0.191363,0.789761,2.744921,0.626354,1.293186,1.053749
3,src_cell_4,2.998839,4.636264,5.173774,-0.925229,0.060790,-0.048825,8.174915,2.997011,6.050070,...,-0.239083,4.261027,1.669982,0.272288,1.411168,1.001428,1.996620,0.948338,2.510993,0.638518
4,src_cell_5,4.570555,5.874580,5.479512,0.014188,0.333612,0.589372,7.492206,3.493306,6.407340,...,-0.314298,2.540325,2.689368,0.644284,0.856031,4.184494,3.759636,0.947633,1.786984,0.662194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471,src_cell_472,3.721997,5.552235,5.560080,-0.008305,-0.064523,0.179723,6.684903,2.469105,4.322515,...,0.341318,4.361195,3.061217,1.039493,0.542610,0.449654,3.788066,1.149309,1.607055,0.390158
472,src_cell_473,3.309967,4.782881,6.786391,0.361498,-0.126596,-0.000873,6.616854,3.097813,4.098359,...,-0.560452,3.478682,2.588885,-0.129434,0.422786,0.385354,4.903189,-0.187262,2.179123,1.524775
473,src_cell_474,6.290468,3.764617,5.525614,2.360743,0.752263,1.033722,6.958898,4.345360,5.699834,...,-0.143118,4.961113,2.410520,0.340330,-0.037555,-0.395240,3.484453,-0.063415,2.886373,0.246049
474,src_cell_475,3.576921,5.394375,6.608699,0.139374,-1.183819,0.827569,7.122319,3.157825,4.257678,...,1.038065,2.851100,1.910870,0.195155,-0.564299,1.878361,3.328660,-0.214998,0.789899,1.091669
475,src_cell_476,4.389014,4.900945,6.157377,1.445826,0.083113,1.430655,7.313094,3.285286,2.961621,...,0.499897,5.301595,1.627906,1.317024,-0.513933,0.535867,4.554086,-0.270236,3.022927,1.497460

In [4]:
output = ""

In [5]:
with open("output.txt", "w") as f:    
    for index, row in data.iterrows():
        output = f"{row['Unnamed: 0']}: "
        for col in data.columns:
            if col != 'Unnamed: 0':
                output += f"{col}:{row[col]}; "
        # print(output.strip())
        f.write(output.strip() + "\n")